eureka:
    client:
       register-with-eureka: true
          fetch-registery: true
           service-url:  
             defaultZone: http://9localhost:8761//eureka
           instance:
              hostname: localhost
           
              
